name: PR Java Tests

on:
  pull_request:
    branches:
      - main  

jobs:
  build-and-test:
    name: Build & Test Java CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  
          java-version: '17'       
          cache: maven

      - name: Verify Java & Maven Installation
        run: |
          java -version
          mvn -version

      - name: Grant execute permission for build.sh
        run: chmod +x build.sh 

      - name: Run build script
        run: ./build.sh  

      - name: Run Build Script (Auto Answer Input)
        run: echo -e "y\nsrc.main.java.com.Main" | ./build.sh

      - name: Run tests
        run: mvn test  

      - name: Run CLI Tool Tests for user
        run: ./user_test.sh

      - name: Run CLI Tool Tests for listing
        run: ./listing_test.sh


